+incdir+./includes
./includes/xctcmsg_pkg.sv
./includes/xctcmsg_piton_pkg.sv
./rtl/loopback_interceptor.sv
./rtl/network/bus_interface.sv
./rtl/network/bus_adapter.sv
./rtl/network/openpiton_interface.sv
./rtl/network/openpiton_adapter.sv
./rtl/mbox.sv
./rtl/postoffice.sv
./rtl/request_decoder.sv
./rtl/send_queue.sv
./rtl/receive_queue.sv
./rtl/writeback_arbiter.sv
./rtl/commit_safety_unit.sv
./rtl/xctcmsg.sv